### ISSUE TITLE
Allow configuration via environment variables

### ISSUE THREAD

**Issue by treyhunner** [nitaigao/gulp-s3#23]
Like the grunt-s3 plugin [allows](https://github.com/pifantastic/grunt-s3#environment-variables).

**Comment by easement** [comment]
I would agree. did you ever figure this out @treyhunner

**Comment by treyhunner** [comment]
@easement I haven't tried again yet

**Comment by gilesbutler** [comment]
Hey Guys,

I just came across this myself. I'm not actually using it in the end but this worked for me. Create a aws object above your gulp task rather than JSON parsing the aws.json file. Then you can use process.env.VARIABLE_NAME to get whichever variable you're looking for.
````
var aws = {
  'key':    process.env.AWS_ACCESS_KEY,
  'secret': process.env.AWS_SECRET_KEY,
  'bucket': 'YOUR BUCKET NAME',
  'region': 'us-west-2'
};
````
Hope it helps :)

**Comment by DigitallyBorn** [comment]
You could always read a file based on an environment variable. This could let you have premade configuration files for specific environments.

Something like:
```var aws = require('./aws.' + process.env.NODE_ENV + '.json')```

**Comment by nitaigao** [comment]
Yep, updated docs as per @gilesbutler's answer
