### ISSUE TITLE
SVG uploaded with wrong MIME type

### ISSUE THREAD

**Issue by hungsu** [nitaigao/gulp-s3#36]
Hi,

Whenever I upload SVG files with gulp-s3, they have MIME "text/plain" rather than "image/svg+xml". I'm using gulp-s3 version 0.2.0.

**Comment by frandroid** [comment]
@hungsu , this module uses the npm mime module to determine the extension; try using the module on its own to see if the bug is there, and report your bug with that module if that's the case:
https://www.npmjs.com/package/mime
