### ISSUE TITLE
Delete files on sync

### ISSUE THREAD

**Issue by Serhioromano** [nitaigao/gulp-s3#39]
Acording to AWS docs

http://docs.aws.amazon.com/cli/latest/userguide/using-s3-commands.html

You can use `--delete` parameter when sync with s3 and that will delete all files in bucket that are not presented in sync. 

This is very useful feature to keep things neat. 

Possible to implement?

**Comment by vaibhavkumar-sf** [comment]
How can we delete old files from s3 folder while syncing ?
