### ISSUE TITLE
Errors are undetectable

### ISSUE THREAD

**Issue by toolness** [nitaigao/gulp-s3#47]
Hey, I noticed in the [code](https://github.com/nkostelnik/gulp-s3/blob/master/index.js#L52-L59) that errors appear to be logged but then nothing is done about them:

``` js
      client.putBuffer(file.contents, uploadPath, headers, function(err, res) {
        if (err || res.statusCode !== 200) {
          gutil.log(gutil.colors.red('[FAILED]', file.path + " -> " + uploadPath));
        } else {
          gutil.log(gutil.colors.green('[SUCCESS]', file.path + " -> " + uploadPath));
          res.resume();
        }
      });
```

It would be nice if an error event or something was emitted, so that gulp tasks could raise errors instead of having the process exit with status code 0 even though things went amiss.

**Comment by tomdidom** [comment]
+1

**Comment by mpelzsherman** [comment]
+1

**Comment by christianhaller** [comment]
+1

**Comment by nicholascloud** [comment]
+1

**Comment by mfonda** [comment]
+1

**Comment by nitaigao** [comment]
Fixed in: https://github.com/nitaigao/gulp-s3/commit/f3a46731b608b88588280ae23c0feefa080e2c3f

**Comment by christianhaller** [comment]
Thank you @nitaigao :)
