### ISSUE TITLE
Always getting FAILED (StatusCode 400)

### ISSUE THREAD

**Issue by Inoverse** [nitaigao/gulp-s3#53]
I'm always getting an FAILED error. If I take a look into the index.js I  can see an status code of 400.
Anyone else having this issue and/or a solution?

**Comment by j-norwood-young** [comment]
Also having this issue.

**Comment by rgcunha** [comment]
same here. any thoughts on what might be?

**Comment by rgcunha** [comment]
In my case the error was related with the region where the bucket was being hosted ( Frankfurt ). Changed it to Ireland and it's already working.

**Comment by cruzlutor** [comment]
Hi, in my case my Mac clock was ahead, You only have to adjust the time in your machine and it work again

Here more information
http://www.bucketexplorer.com/documentation/amazon-s3--difference-between-requesttime-currenttime-too-large.html

**Comment by subinsebastien** [comment]
This could also be the reason #62

**Comment by lucasdavila** [comment]
It may be a problem with your credentials, or with the bucket and/or region.

Take a looks here http://docs.aws.amazon.com/general/latest/gr/rande.html if you aren't sure about the region you should use).

Also, as a contribution suggestion, printing the error details would make the problem solution easier, if possible.

**Comment by nitaigao** [comment]
Ive updated the error output with the status code and error object returned from AWS.

As this is a year old, if it comes up again we can open a new issue.
