### ISSUE TITLE
Random FAILED assets

### ISSUE THREAD

**Issue by corbanb** [nitaigao/gulp-s3#55]
Been using this plugin for quite sometime and never had issues. Recently I have been getting a lot of random assets failing. Anyone know what would cause this? Any help would be great.

**Comment by adrianfalleiro** [comment]
Do you know what the status code is?

**Comment by alexmccabe** [comment]
I'm having a similar issue, I have no errors coming back but some files are not being uploaded. If I remove a directory from my local machine then one of the ones that hasn't been uploaded will then get published. I have 89 files in total. This should not be enough to stop files from being published.

**Comment by corbanb** [comment]
I moved over to another module and it all worked fine. Seemed like it was caused by the connector being used under the hood here. Never had much time to overly debug.

Here is my task for anyone in a hurry. :sweat_smile: 

```javascript
var awspublish = require('gulp-awspublish');
var gulp = require('gulp');
var rename = require('gulp-rename');

var awsOptions = {
  region: config.env.s3.region,
  accessKeyId: config.env.s3.key,
  secretAccessKey: config.env.s3.secret,
  endpoint: 'http://s3.amazonaws.com',
  maxRetries: 2,
  params: {
    Bucket: config.env.s3.bucket
  }
};

var publisher = awspublish.create(awsOptions);

var headers = {
  'Cache-Control': 'max-age=300,s-maxage=900,no-transform,public',
  'x-amz-acl': 'public-read'
};


gulp.task('publish', function() {
    return gulp.src('./.tmp/public/**/!(*.sass||*.less|*.scss|*.pdf|*.md|*.json|*.html|LICENSE|*.markdown|*.php)')
        .pipe(rename(function(path) {
          path.dirname = '/assets/' + path.dirname
        }))
        .pipe(awspublish.gzip())
        .pipe(publisher.publish(headers))
        .pipe(publisher.cache())
        .pipe(awspublish.reporter({
          states: ['create', 'update', 'delete']
        }));
})
```

**Comment by alexmccabe** [comment]
I would say this package is dead, it hasn't been modified in 2 years. Time to move on, shame. I've even been thinking of dumping gulp entirely and just running node as my build tool.
