### ISSUE TITLE
Specify charset for HTML files

### ISSUE THREAD

**Issue by dingledow** [nitaigao/gulp-s3#56]
Is there a way to set the `charset` to `UTF-8` only on files with a `Content-Type: text/html`?

These are my settings currently:

```
gulp.task('deploy', function() {
  var awsConfig = require('./lib/config/aws.js');
  var s3Options = {
    headers: {
      'Cache-Control': 'max-age=3600, no-transform, public'
    }
  };
  gulp.src('./public/**')
    .pipe(gzip())
    .pipe(gulpS3(awsConfig, s3Options));
});
```

**Comment by adrianfalleiro** [comment]
If you add an `encoding: 'utf8'` to your `s3Options` object - the plugin should append `charset=utf8` to the  `Content-Type` header. 

You could probably do this for only `text/html` files by having separate gulp task for it.
