### ISSUE TITLE
Event 'end' emit

### ISSUE THREAD

**Issue by flodonsky** [nitaigao/gulp-s3#67]
Can you please have the EventSteam emit the "end" event? So when binding to the standard event, my gulp tasks can execute the 'done' callback and can continue synchronously as I'm codependent on this completion to cleanup.

I've forked the repo and may try myself if you're unavailable, do you actually manage pull requests?

**Comment by nitaigao** [comment]
Hey, that should be fixed now in the latest version `0.11.0`

**Comment by relicmelex** [comment]
No, yeah not working....That was the version I was trying to use.... no emit.

Wrote a promise based solution directly with knox in favor of less dependancies. Cheers.

**Comment by flodonsky** [comment]
Yeah... no not working in that version, that's the one I was trying to use.

Ended up writing my own `fs.reader` w/ `glob` and `knox` in favor of handling the 'done' callback in gulp with more options, and less overall dependancies.
